### ISSUE TITLE
Compatibilty Error

### ISSUE THREAD

**Issue by NextStarIndustries** [linuxgurugamer/StockDefaultSettings#2]
KSP 1.10.1 has error not compatible with this version of KSP freezing up loading.

**Comment by linuxgurugamer** [comment]
I rather doubt that, since I developed and tested it on a 1.10.1 install.
And, please post anything further about this in the thread, where both you and others can see the problem and the answer.
Given the comments in the thread, I can assume that others have tried and used it without any issue.

The only thing I can think of is to check the dependencies, which are also listed in the thread.

Please provide a Player.log file for analysis when you post on the thread: https://forum.kerbalspaceprogram.com/index.php?/topic/197500-18x-19x-110x-stock-default-settings/
